### ISSUE TITLE
Peer Review # 1

### ISSUE THREAD

**Issue by younazhao** [chuyun2024/School-Shooting-Casualty-Analysis#1]
Opening statement summary

I am peer-reviewing Chu Yun's paper on US School Shooting Predictions and Solutions.

Strong positive points

The paper has a very complex amount of codes. The simulation and tests were very well performed. The model is also very extended by using random forests. I liked the visual graphs that she provided in the paper and it gave us a perfect sense of the numbers of causality by states. She has provided all the libraries she used and cited on the reference page. 

Critical improvements needed

Formatting still needs to improve, the introduction and abstract are missing. Don't forget to delete unused files in the folder. The pdf contained several sections that needed to be changed for the final submission. Missing discussion section, Appendix and Results. Don't forget to add sections to show aspects of survey, sampling or observational data. 

Suggestions for improvement:

Add more plots as needed in the results section
How Solution could be provided in this paper
How random forest would be best model for your research compared to other models
Figure name could be changed
What are the main factors causing School shooting
Don't forgot to modify README section

Evaluation:

Evaluation:
R/Python cited (1/1 pts)
R is cited
Data cited (1/1 pts)
Data is cited, don't forget to correct the cross reference in paper 
Class paper (1/1 pts)
No sign of a class paper
LLM documentation (1/1 pts)
LLM needs to be updated 
Title (1/2 pts)
The title could be better (Ex: US - United States
Author, date, and repo (2/2 pts)
All included
Abstract (0/4 pts)
Missing abstract
Introduction (0/4 pts)
Missing Introduction
Estimand (0/1 pts)
Missing Estimand
Data (7/10 pts)
Add more explanation to the Data
Measurement (3/4 pts)
Missing details
Model (5/10 pts)
More explanations are needed
Results (0/10 pts)
Missing results
Discussion (0/10 pts)
Missing discussion
Prose (3/6 pts)
Should add more words
Cross-references (1/1 pts)
Make sure to type the correct labels and words
Captions (1/2 pts)
Add more captions
Graphs/tables/etc (2/4 pts)
Some are missing
Surveys, sampling, and observational data appendix (0/10 pts)
More information needed
Referencing (3/4 pts)
Good reference 
Commits (2/2 pts)
Commits are well-maintained
Sketches (0/2 pts)
Sketches missing
Simulation (4/4 pts)
Good simulations
Tests (4/4 pts)
Tests are good
Parquet (0/1 pts)
Parquet missing
Reproducible workflow (4/4 pts)
Good structure
Enhancements (4/4 pts)
Good enhancements
Miscellaneous (3/3 pts)
Good overall

Estimated overall mark:
53 out of 112.

Any other comments:
Great paper as a first draft!

**Comment by chuyun2024** [comment]
Hi Youna!

Big thank you for your feedback! The aspects you mentioned are added/modified/improved in my paper :)
