### ISSUE TITLE
Peer Review - Sarah #2

### ISSUE THREAD

**Issue by sarahhhh02** [chuyun2024/School-Shooting-Casualty-Analysis#2]
Summary
This repo includes an analysis for the 2025 US school shooting along with possible predictions and solutions. It contains codes relevant to the topic that dives further into how leveraging forecast may shape policy and protect communities. 

Strong positive points:
- Your measurement is clear and concise!
- The analysis dataset is saved as a parquet file
- Repo is organized with throughly written code styles, preambles, comments, and nice structure

Critical improvements needed:
- There is no LLM documentation regarding the topic of research. Although there is still a documentation on your README and usage.txt, there is no connection to your topic! It would be best to add so you don't get a zero.
- Add an abstract, introduction, estimand, results, appendix, and discussion for your paper!
- Sketches should be added that are relevant to your topic
- README is not entirely finished! Can update LLM usage and get rid of the check boxes. The Overview can be a little more detailed with where the data is from as such. 

Suggestions for improvement:
- This is just a suggestion, although the title is informative and clear, the second part of the title can be a little more concise. It can be a bit shorter and concise! Of course this is just a suggestion
- There were some minor grammar and punctuation mistakes that can be easily fixed! 
- Some of the cross references are correctly done while some are with question marks! 
- 

Evaluation:
R/Python cited (1/1 pts)
[R is properly cited]
Data cited (1/1 pts)
[Data is cited in the paper and in reference.bib]
Class paper (1/1 pts)
[There is no indication that this is a class paper]
LLM documentation (0/1 pts)
[There is no LLM documentation regarding topic]
Title (2/2 pts)
[The title is informative]
Author, date, and repo (2/2 pts)
[All of them are included in the paper]
Abstract (0/4 pts)
[The abstract is empty and incomplete]
Introduction (1/4 pts)
[There is a outline of what the introduction should include but it is not complete]
Estimand (0/1 pts)
[Not included yet]
Data (10/10 pts)
[all data is documented]
Measurement (4/4 pts)
[measurement is included]
Model (10/10 pts)
[Model is there in both the paper and coding]
Results (0/10 pts)
[Results are incomplete]
Discussion (0/10 pts)
[Discussion is incomplete]
Prose (5/6 pts)
[There are some minor mistakes]
Cross-references (1/1 pts)
[Cross-references are there]
Captions (2/2 pts)
[Good  captions]
Graphs/tables/etc (4/4 pts)
[necessary graphs/tables/etc are included]
Surveys, sampling, and observational data appendix (0/10 pts)
[Not included yet]
Referencing (4/4 pts)
[References are all added in references.bib]
Commits (2/2 pts)
[Commits are all meaningful]
Sketches (0/2 pts)
[not included]
Simulation (4/4 pts)
[Simulation is coded]
Tests (4/4 pts)
[Tests are coded concisely]
Parquet (1/1 pts)
[analysis data is parquet]
Reproducible workflow (3/4 pts)
[Comment]
Enhancements (4/4 pts)
[Used R package]
Miscellaneous (1/3 pts)
[The paper is not entirely finished and are missing big parts in the paper]
Estimated overall mark:
[67] out of [112].

**Comment by chuyun2024** [comment]
Hi Sarah,

Thank you so much for your peer review!! Your feedbacks are really helpful and I improved my paper based on your review:)
